Dockerfile
build.gradle

EM-1288
```
[ ] Yes
[x] No
```

update CNP dependencies

---

src/main/java/uk/gov/hmcts/reform/em/orchestrator/financialremedyservice/FinancialRemedyAddCaseBundleService.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/financialremedyservice/FinancialRemedyBundlePopulator.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/financialremedyservice/FinancialRemedyCaseVerifierConfiguration.java
src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/financialremedy/FinancialRemedyAddCaseBundleServiceTest.java
src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/financialremedy/FinancialRemedyBundlePopulatorTest.java

FR-784: Integrating Financial remedy with ccd bundling service

---

docker-compose.yml

Update docker-compose with correct env var names for IDAM and S2S URIs.
```
[ ] Yes
[ ] No
```

docker update env var names

---

src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/CcdPrehookScenarios.java
src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/CcdStitchScenarios.java

Print statements to show request and response bodies - this is to get the stitched Document URIs from the DM store
```
[ ] Yes
[x] No
```

Add f test print statements

---

src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/CcdStitchScenarios.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/CcdStitchBundleCallbackController.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/NewBundleController.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/ccdcallbackhandler/CcdCallbackHandlerService.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/ccdcallbackhandler/CcdCallbackHandlerServiceImpl.java
src/test/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/CcdStitchBundleCallbackControllerTest.java
src/test/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/NewBundleControllerTest.java
src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/ccdcallbackhandler/CcdCallbackHandlerServiceImplTest.java

None
Fix typo that happens a lot, where Ccd is spelt Cdd.
```
[ ] Yes
[x] No
```

fix cdd typo

---

charts/em-ccd-orchestrator/values.yaml
dependency-check-suppressions.xml

hit-liveness endpoint

---

src/aat/java/uk/gov/hmcts/reform/em/orchestrator/testutil/TestUtil.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/stitching/StitchingService.java
src/test/java/uk/gov/hmcts/reform/em/orchestrator/stitching/StitchingServiceTest.java

add binary suffixes

---

src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/AutomatedBundlingScenarios.java
src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/CcdStitchScenarios.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/AutomatedCaseUpdater.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/configuration/BundleConfigurationFolder.java
src/main/resources/bundleconfiguration/example.yaml
src/test/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/AutomatedCaseUpdaterTest.java
src/test/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/configuration/LocalConfigurationLoaderTest.java

https://tools.hmcts.net/jira/browse/EM-1654
Add support for nested folders in the configuration file
```
[ ] Yes
[x] No
```

Add support for nested folders

---

src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/AutomatedBundlingScenarios.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/AutomatedCaseUpdater.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/dto/CcdBundleDTO.java

https://tools.hmcts.net/jira/browse/EM-1522
Add hasCoversheets, hasTableOfContents and hasFolderCoversheets options to configuration
```
[ ] Yes
[x] No
```

Hook up configuration options

---

README.md
build.gradle
src/main/java/uk/gov/hmcts/reform/em/orchestrator/CliApplication.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/AutomatedCaseConfiguration.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/command/ValidateYamlCommand.java
src/test/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/command/ValidateYamlCommandTest.java
src/test/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/CcdCloneBundleControllerTest.java
src/test/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/CcdStitchBundleCallbackControllerTest.java
src/test/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/NewBundleControllerTest.java

retry for k8s reasons
```
[ ] Yes
[ ] No
```

Added yaml validation task

---

src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/configuration/BundleConfigurationDocument.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/configuration/BundleConfigurationDocumentSet.java

make constructors for yaml parameters

---

build.gradle
src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/CcdStitchScenarios.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/dto/CcdBundleDTO.java
src/test/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/AutomatedCaseUpdaterTest.java
src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/CcdBundleStitchingServiceTest.java
src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/JsonNodesVerifierTest.java
src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/example/ExampleBundlePopulatorTest.java
src/test/java/uk/gov/hmcts/reform/em/orchestrator/stitching/mapper/StitchingDTOMapperTest.java

Added in a limit for descripition field. Added a test case to test the same.

Added character limit and updated functional testcase

---

charts/em-ccd-orchestrator/Chart.yaml
charts/em-ccd-orchestrator/requirements.yaml

no
use java base image from hmctspublic chart registry, instead of from hmcts chart registry
```
[ ] Yes
[x] No
```

update java base image in microservice chart

---

build.gradle
pacts/em_ccd_orchestrator-idam_api.json
src/contractTest/java/uk/gov/hmcts/reform/em/orchestrator/IdamConsumerTest.java

sidam pact

---

charts/em-ccd-orchestrator/Chart.yaml
infrastructure/main.tf
infrastructure/output.tf

https://tools.hmcts.net/jira/browse/EM-2032
Replaced the vault_uri with key_vault_id

Replaced the vault_uri with key_vault_id

---

Jenkinsfile_CNP
infrastructure/prod.tfvars

Updated idam URL, added in DNS value and removed unused function

Updated idam URL, added in DNS value and removed unused function

---

charts/em-ccd-orchestrator/Chart.yaml
charts/em-ccd-orchestrator/values.yaml
infrastructure/main.tf
src/main/resources/bootstrap.yaml

switch vaults

---

charts/em-ccd-orchestrator/values.aat.template.yaml

add aat callback

---

infrastructure/aat.tfvars
infrastructure/main.tf
infrastructure/variables.tf

disable ase

---

src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/CcdStitchScenarios.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/AutomatedCaseUpdater.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/AutomatedStitchingExecutor.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/CcdBundleStitchingService.java
src/test/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/AutomatedStitchingExecutorTest.java
src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/CcdBundleStitchingServiceTest.java

Starts the stitching asynchronously

Asyn stitching

---

Jenkinsfile_CNP

disable ase prd

---

src/main/resources/bundleconfiguration/complex-example.yaml

Add pagination and page number format to complex yaml

---

infrastructure/aat.tfvars
infrastructure/main.tf
infrastructure/variables.tf

disable prod ASE

---

src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/AsyncCcdBundleStitchingService.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/CcdBundleStitchingService.java

EM-2242: Add coverpage template data when async bundling

---

src/main/resources/bundleconfiguration/complex-example.yaml

Update template for cover page in complex yaml file

---

charts/em-ccd-orchestrator/Chart.yaml

https://tools.hmcts.net/jira/browse/EM-2238
```
[ ] Yes
[ ] No
```

EM-2238 add api version to chart

---

charts/em-ccd-orchestrator/Chart.yaml
charts/em-ccd-orchestrator/requirements.yaml
charts/em-ccd-orchestrator/values.aat.template.yaml
charts/em-ccd-orchestrator/values.preview.template.yaml
charts/em-ccd-orchestrator/values.yaml

https://tools.hmcts.net/jira/browse/EM-2256

Removed alias related lines

---

charts/em-ccd-orchestrator/Chart.yaml
charts/em-ccd-orchestrator/values.yaml

https://tools.hmcts.net/jira/browse/EM-2299

Updated the respective URL's

---

src/main/resources/bundleconfiguration/complex-example.yaml

Rename field in complex yaml

---

src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/BundleFactory.java

https://tools.hmcts.net/jira/browse/EM-2329

Added in lines to populate 2 attributes for bundle config

---

charts/em-ccd-orchestrator/Chart.yaml
charts/em-ccd-orchestrator/values.aat.template.yaml
charts/em-ccd-orchestrator/values.preview.template.yaml
charts/em-ccd-orchestrator/values.yaml

revert move vaults to templates so perftest builds

---

charts/em-ccd-orchestrator/Chart.yaml
charts/em-ccd-orchestrator/values.aat.template.yaml
charts/em-ccd-orchestrator/values.preview.template.yaml
charts/em-ccd-orchestrator/values.yaml

move vaults to templates so perftest builds

---

src/aat/resources/automated-case.json
src/aat/resources/documents-case.json
src/aat/resources/filename-case.json
src/aat/resources/invalid-automated-case.json
src/aat/resources/prehook-case.json
src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/BundleFactory.java
src/test/resources/case-data2.json
src/test/resources/case-one-eligible-one-not-eligible.json
src/test/resources/case-one-eligible.json
src/test/resources/case-one-not-eligible.json
src/test/resources/case-two-eligible.json
src/test/resources/case.json
src/test/resources/documents-case.json

- Correct the date format in the example JSON files
- Switch the handling of date parsing to expect a string

update ccd case dates and bundle factory date handling

---

charts/em-ccd-orchestrator/Chart.yaml
charts/em-ccd-orchestrator/values.aat.template.yaml
charts/em-ccd-orchestrator/values.preview.template.yaml
charts/em-ccd-orchestrator/values.yaml

update appl.yaml with appinsights

---

src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/AutomatedBundlingScenarios.java
src/main/resources/bundleconfiguration/f-tests-1-flat-docs.yaml

Make yaml change  for Jamil

---

src/main/resources/bundleconfiguration/sscs-demo-bundle.yaml

Update yaml for sscs demo bundle as per Jamil request

---

src/main/resources/bundleconfiguration/sscs-demo-bundle.yaml

Changing paginationStyle for sscs yaml

---

charts/em-ccd-orchestrator/Chart.yaml
charts/em-ccd-orchestrator/values.aat.template.yaml
charts/em-ccd-orchestrator/values.preview.template.yaml
charts/em-ccd-orchestrator/values.yaml

move vault back to templates

---

Jenkinsfile_CNP

Updated the vault product name

Updated the vault product name

---

config/owasp/dependency-check-suppressions.xml

Suppressed vulnerabilities

---

infrastructure/main.tf

Commented the vault secret copying bit

Commented the vault secret copying bit

---

charts/em-ccdorc/values.preview.template.yaml

Updated RG name

---

README.md

retrigger-build-to-fix-url-issue
```
[ ] Yes
[x] No
```

retrigger-build-to-fix-url-issue

---

src/main/resources/bundleconfiguration/sscs-bundle-config.yaml

https://tools.hmcts.net/jira/browse/SSCS-7120

Add regex to bundle yaml

---

infrastructure/main.tf

re enable vault secret copy

---

infrastructure/main.tf

disable vault secret copy

---

infrastructure/main.tf

Re enable vaultcopy

---

infrastructure/main.tf

add AI secret copy

---

Jenkinsfile_CNP
charts/em-ccdorc/values.preview.template.yaml
config/owasp/dependency-check-suppressions.xml

remove dockerbuild and aadID

---

src/main/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/StitchingCompleteCallbackController.java

EM-2395: Add check to see if the Boolean wrapper value is null

---

src/aat/java/uk/gov/hmcts/reform/em/orchestrator/testutil/ExtendedCcdHelper.java

Em 2395 alter idam email account used

---

src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/AutomatedCaseUpdater.java

Use jurisdiction instead of case type id for SSCS

---

charts/em-ccdorc/Chart.yaml
charts/em-ccdorc/requirements.yaml

update Javachart. Bump chart ver

---

Jenkinsfile_CNP

Move swagger publishing step

---

Jenkinsfile_CNP
charts/em-ccdorc/Chart.yaml
charts/em-ccdorc/values.yaml
docker-compose-dependencies.yml
docker-compose.yml
infrastructure/demo.tfvars
infrastructure/output.tf
infrastructure/preview.tfvars
infrastructure/prod.tfvars
infrastructure/sprod.tfvars
infrastructure/variables.tf
src/aat/resources/application.yml
src/main/java/uk/gov/hmcts/reform/em/orchestrator/config/security/SecurityConfiguration.java
src/main/resources/application.yaml

Removed the issuer override bits

Removed the issuer override bits

---

Jenkinsfile_CNP
charts/em-ccdorc/Chart.yaml
charts/em-ccdorc/values.yaml

Updated openId endpoint

---

src/main/resources/bundleconfiguration/complex-example.yaml

Update complex yaml example to include new features

---

src/main/java/uk/gov/hmcts/reform/em/orchestrator/stitching/dto/DocumentImage.java
src/test/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/BundleFactoryTest.java

EM-1781: Migrate int to Integer

---

charts/em-ccdorc/Chart.yaml
charts/em-ccdorc/values.aat.template.yaml
charts/em-ccdorc/values.preview.template.yaml
charts/em-ccdorc/values.yaml

Moved secrets to values.yaml

---

Jenkinsfile_CNP
Jenkinsfile_parameterized
build.gradle
src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/BaseTest.java

EM-2719: Serenity Reporting  CCD-Orchestrator

EM-2719: Serenity Reporting  CCD-Orchestrator

---

Jenkinsfile_CNP
build.gradle
pacts/em_ccd_orchestrator-idam_api.json
src/contractTest/java/uk/gov/hmcts/reform/em/orchestrator/IdamConsumerTest.java

JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/EM-2886
Change description
Integrate Pact with pipeline and publish to pact broker
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[X ] No

Em 2886 integrate pact pipeline

---

pacts/em_ccd_orchestrator-idam_api.json
src/contractTest/java/uk/gov/hmcts/reform/em/orchestrator/IdamConsumerTest.java

https://tools.hmcts.net/jira/browse/EM-2886
Pact json request body fix
```
[ ] Yes
[ X ] No
```

EM-2886 Fix for POST request body generation in pact json

---

Jenkinsfile_CNP
config/owasp/dependency-check-suppressions.xml

remove installcharts

---

config/owasp/dependency-check-suppressions.xml
src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/BundleFactory.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/configuration/BundleConfiguration.java
src/main/resources/bundleconfiguration/iac-bundle-config.yaml
src/test/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/BundleFactoryTest.java
src/test/resources/case-data6.json

https://tools.hmcts.net/jira/browse/EM-2994

Added in  changes for documentLinkName

---

src/main/resources/bundleconfiguration/iac2-bundle-config.yaml

Added in another yaml config file

Added in another yaml config file

---

src/main/resources/bundleconfiguration/iac-hearing-bundle-config.yaml

https://tools.hmcts.net/jira/browse/RIA-3116
IAC final hearing bundle configuration added
```
[ ] Yes
[X] No
```

RIA-3116: IAC final hearing bundling config

---

src/main/resources/bundleconfiguration/iac-hearing-bundle-config.yaml

https://tools.hmcts.net/jira/browse/RIA-3116§
IAC final hearing bundling config - structured using folders
```
[ ] Yes
[X] No
```

RIA-3116: IAC final hearing bundling config - structured using folders

---

src/main/java/uk/gov/hmcts/reform/em/orchestrator/config/SwaggerConfiguration.java

Updated Swagger with Auth & Service Auth headers

Updated Swagger with Auth & Service Auth headers

---

Dockerfile
build.gradle
config/owasp/dependency-check-suppressions.xml
src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/BundleFactory.java
src/main/resources/bundleconfiguration/iac-hearing-bundle-config.yaml
src/test/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/AutomatedCaseUpdaterTest.java

https://tools.hmcts.net/jira/browse/EM-3004

Em 3004 java11 upgrade

---

src/main/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/NewBundleController.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/ccdapi/CcdDataApiCaseUpdater.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/ccdapi/CcdDataApiEventCreator.java

https://tools.hmcts.net/jira/browse/EM-3101

Added in logging

---

Jenkinsfile_nightly
build.gradle

EM-2747 Adding config for Mutation Tests

EM-2747 Adding config for Mutation Tests

---

Jenkinsfile_nightly

https://tools.hmcts.net/jira/browse/EM-3073

Updated nightly build file

---

build.gradle
src/aat/java/uk/gov/hmcts/reform/em/orchestrator/smoke/SmokeTest.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/WelcomeController.java
src/test/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/WelcomeControllerTest.java

https://tools.hmcts.net/jira/browse/EM-3116

Updated em-test-helper

---

.dependabot/config.yml
.github/renovate.json
.github/stale.yml

https://tools.hmcts.net/jira/browse/EM-3187

Updated bot config

---

build.gradle
charts/em-ccdorc/Chart.yaml
charts/em-ccdorc/requirements.yaml
charts/em-ccdorc/values.yaml
config/owasp/dependency-check-suppressions.xml
gradle/wrapper/gradle-wrapper.properties
src/main/java/uk/gov/hmcts/reform/em/orchestrator/config/security/SecurityConfiguration.java

https://tools.hmcts.net/jira/browse/EM-3092

Updated Spring boot version

---

src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/AutomatedBundlingScenarios.java
src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/AutomatedBundlingWithCallbacks.java
src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/CcdCloneScenarios.java
src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/CcdPrehookScenarios.java
src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/CcdStitchScenarios.java
src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/OpenIdConnectScenarios.java
src/aat/java/uk/gov/hmcts/reform/em/orchestrator/retry/RetryRule.java

EM-3263 - EM-CCD: Add retry logic for failing functional test cases

---

config/owasp/dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/EM-3275

Updated vulnerability

---

build.gradle
config/owasp/dependency-check-suppressions.xml

Resolved CVE-2020-13943, CVE-2007-5615, and CVE-2020-13956
```
[ ] Yes
[ ] No
```

Resolved Vulnerabilities

---

src/main/resources/bundleconfiguration/sscs-bundle-edited-config.yaml
src/main/resources/bundleconfiguration/sscs-bundle-unedited-config.yaml
src/main/resources/bundleconfiguration/sscs-bundle-welsh-edited-config.yaml
src/main/resources/bundleconfiguration/sscs-bundle-welsh-unedited-config.yaml

https://tools.hmcts.net/jira/browse/SSCS-8458
```
[ ] Yes
[x] No
```

sscs-8458 New config for edited bundles

---

build.gradle

EM-3428-EM-CCD: Failed to generate serenity report

---

src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/CcdStitchScenarios.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/config/Constants.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/dto/CcdBundleDTO.java
src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/CcdBundleStitchingServiceTest.java

https://tools.hmcts.net/jira/browse/EM-3418

Increased field length restriction

---

build.gradle
config/owasp/dependency-check-suppressions.xml

Em 3513 update pact jupiter related dependencies

Em 3513 update pact jupiter related dependencies

---

build.gradle
src/main/resources/bundleconfiguration/sscs-bundle-config.yaml
src/main/resources/bundleconfiguration/sscs-bundle-edited-config.yaml
src/main/resources/bundleconfiguration/sscs-bundle-unedited-config.yaml
src/main/resources/bundleconfiguration/sscs-bundle-welsh-config.yaml
src/main/resources/bundleconfiguration/sscs-bundle-welsh-edited-config.yaml
src/main/resources/bundleconfiguration/sscs-bundle-welsh-unedited-config.yaml

https://tools.hmcts.net/jira/browse/SSCS-8753

SSCS-8753 Add RIP1 document to bundle

---

src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/CcdPrehookScenarios.java

EM-3629 - EM-CCD-Orchestrator: Fix ignored test cases

---

build.gradle

EM-3640 - EM-CCD-Orchestrator: Pact report not generating

---

src/main/resources/bundleconfiguration/sscs-bundle-edited-config.yaml
src/main/resources/bundleconfiguration/sscs-bundle-unedited-config.yaml
src/main/resources/bundleconfiguration/sscs-bundle-welsh-config.yaml
src/main/resources/bundleconfiguration/sscs-bundle-welsh-edited-config.yaml
src/main/resources/bundleconfiguration/sscs-bundle-welsh-unedited-config.yaml

https://tools.hmcts.net/jira/browse/SSCS-8861

SSCS-8861 Configure Welsh RIP1 doc for bundle

---

charts/em-ccdorc/Chart.yaml
charts/em-ccdorc/values.yaml

N/A
Updated image path
```
[ ] Yes
[X] No
```

Updated image path

---

charts/em-ccdorc/Chart.yaml

N/A
Updated java chart version
```
[ ] Yes
[X] No
```

Updated java chart version

---

src/main/java/uk/gov/hmcts/reform/em/orchestrator/info/BuildInfo.java

https://tools.hmcts.net/jira/browse/EM-3754
Fixed Resource leak
```
[ ] Yes
[X] No
```

Fixed Resource leak

---

docker-compose-dependencies.yml

https://tools.hmcts.net/jira/browse/EM-3803
Updated docker-compose-dependencies
```
[ ] Yes
[X] No
```

Updated docker-compose-dependencies

---

build.gradle
src/main/resources/bundleconfiguration/sscs-bundle-config.yaml
src/main/resources/bundleconfiguration/sscs-bundle-edited-config.yaml
src/main/resources/bundleconfiguration/sscs-bundle-welsh-config.yaml
src/main/resources/bundleconfiguration/sscs-bundle-welsh-edited-config.yaml

Sscs 9290 rip1 in bundle

---

src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/configuration/LocalConfigurationLoader.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/StitchingCompleteCallbackController.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/notification/NotificationService.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/orchestratorcallbackhandler/CcdCallbackBundleUpdater.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/util/StringUtilities.java
src/test/java/uk/gov/hmcts/reform/em/orchestrator/util/StringUtilitiesTest.java

https://tools.hmcts.net/jira/browse/EM-3871
Fixed Resource leak issue
```
[ ] Yes
[X] No
```

Fixed Resource leak issue

---

Jenkinsfile_nightly
build.gradle
config/fortify-client.properties
src/test/resources/logback.xml

https://tools.hmcts.net/jira/browse/EM-3961
Added in Fortify library
```
[ ] Yes
[X] No
```

Added in Fortify library

---

build.gradle
src/main/java/uk/gov/hmcts/reform/em/orchestrator/Application.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/config/ServiceTokenGeneratorConfiguration.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/config/security/SecurityUtils.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/ServiceNameAspect.java
src/test/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/CcdCloneBundleControllerTest.java
src/test/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/CcdStitchBundleCallbackControllerTest.java
src/test/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/NewBundleControllerTest.java
src/test/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/StitchingCompleteCallbackControllerTest.java
src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/ServiceNameAspectTest.java

https://tools.hmcts.net/jira/browse/EM-3974
Added in logging to capture consuming service name
```
[ ] Yes
[X] No
```

Added in logging to capture consuming service name

---

charts/em-ccdorc/Chart.yaml

https://tools.hmcts.net/jira/browse/EM-3994
Updated Chart Java version
```
[ ] Yes
[X] No
```

Updated Chart Java version

---

src/main/resources/bundleconfiguration/iac-upper-tribunal-bundle-config.yaml

[RIA-4351](https://tools.hmcts.net/jira/browse/RIA-4351)
Bundle configuration for new IAC Upper Tribunal bundle.
```
[ ] Yes
[x] No
```

RIA-4351 Upper Tribunal bundle config

---

infrastructure/state.tf

EM-4024
fix terraform provider
```
[ ] Yes
[x] No
```

EM-4024: fix terraform provider

---

build.gradle

EM-4060
fix checkstyle removed ignore failure
```
[ ] Yes
[ x] No
```

EM-4060: fix checkstyle removed ignore failure

---

build.gradle

EM-4060
Spring boot upgrade version 2.5.5
```
[ ] Yes
[x] No
```

EM-4060: spring boot upgrade version 2.5.5

---

build.gradle

EM-4060
downgrade junit 5
```
[ ] Yes
[x] No
```

EM-4060: downgrade junit 5

---

src/main/java/uk/gov/hmcts/reform/em/orchestrator/stitching/StitchingService.java

na
fix deprecated method
```
[ ] Yes
[x] No
```

fix deprecated method

---

src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/ServiceNameAspect.java
src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/ServiceNameAspectTest.java

https://tools.hmcts.net/jira/browse/EM-4065
Resolve Error status with code : 500 for ServiceNameAspect
```
[ ] Yes
[X] No
```

Add InvalidTokenException to ServiceNameAspect and its test class

---

build.gradle

https://tools.hmcts.net/jira/browse/EM-4113
Resolve CVE-2021-22044
```
[ ] Yes
[X] No
```

Em 4113 resolve vulnerabilities

---

README.md
charts/em-ccdorc/values.preview.template.yaml

N/A
Em 3668 remove stitching pr url
```
[ ] Yes
[X] No
```

Em 3668 remove stitching pr url

---

src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/DefaultUpdateCaller.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/util/StringUtilities.java

https://tools.hmcts.net/jira/browse/EM-4155
Fixed fortify issue
```
[ ] Yes
[X] No
```

Fixed fortify issue

---

src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/AutomatedStitchingExecutor.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/CcdBundleStitchingService.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/DefaultUpdateCaller.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/stitching/StitchingService.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/util/StringUtilities.java
src/test/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/AutomatedStitchingExecutorTest.java
src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/CcdBundleStitchingServiceTest.java
src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/DefaultUpdateCallerTest.java
src/test/java/uk/gov/hmcts/reform/em/orchestrator/stitching/StitchingServiceTest.java

https://tools.hmcts.net/jira/browse/EM-4156
Added in logs for caseId & documentTask
```
[ ] Yes
[X] No
```

Added in logs for caseId & documentTask

---

src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/SecureCcdStitchScenarios.java

https://tools.hmcts.net/jira/browse/EM-4162
Ignore tests involving CDAM to investigate build failures
```
[ ] Yes
[X] No
```

Ignore tests involving CDAM

---

build.gradle
src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/configuration/BundleConfigurationSortOrder.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/domain/enumeration/ImageRendering.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/domain/enumeration/ImageRenderingLocation.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/domain/enumeration/PageNumberFormat.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/ServiceNameAspect.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/DefaultUpdateCaller.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/stitching/StitchingService.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/util/StringUtilities.java

https://tools.hmcts.net/jira/browse/EM-4144
Resolve Sonar issues
```
[ ] Yes
[X] No
```

Resolve Sonar issues

---

src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/AutomatedCaseUpdater.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/AutomatedStitchingExecutor.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/BundleFactory.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/command/ValidateYamlCommand.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/config/AutomatedCaseConfiguration.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/ccdapi/CcdDataApiCaseUpdater.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/ccdapi/CcdDataApiEventCreator.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/notification/NotificationService.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/orchestratorcallbackhandler/CallbackException.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/orchestratorcallbackhandler/CcdCallbackBundleUpdater.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/stitching/StitchingService.java
src/test/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/AutomatedCaseUpdaterTest.java

https://tools.hmcts.net/jira/browse/EM-4144
Resolved Sonar issues - second iteration
```
[ ] Yes
[X] No
```

Resolved Sonar issues

---

build.gradle
src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/command/ValidateYamlCommand.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/DefaultUpdateCaller.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/ccdapi/CcdDataApiEventCreator.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/notification/NotificationService.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/orchestratorcallbackhandler/CcdCallbackBundleUpdater.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/stitching/StitchingService.java

https://tools.hmcts.net/jira/browse/EM-4144
Added in Sonar ignore rule in build.gradle
```
[ ] Yes
[X] No
```

Added in Sonar ignore rule in build.gradle

---

build.gradle

https://tools.hmcts.net/jira/browse/EM-4144
Enabled sonar check
```
[ ] Yes
[X] No
```

Enabled sonar check

---

src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/SecureCcdStitchScenarios.java

https://tools.hmcts.net/jira/browse/EM-4162
Reverted Ignore tests involving CDAM change
```
[ ] Yes
[X] No
```

Reverted Ignore tests involving CDAM change

---

build.gradle

https://tools.hmcts.net/jira/browse/EM-4207
Excluded tests from Sonar
```
[ ] Yes
[X] No
```

Excluded tests from Sonar

---

Dockerfile
bin/start-local-environment.sh
build.gradle
docker-compose-dependencies.yml
src/aat/resources/application.yml
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/EM-4224
Reverted java 17 version changes to fix failing mutation tests
```
[ ] Yes
[X] No
```

Reverted java 17 version changes

---

bin/start-local-environment.sh
docker-compose-dependencies.yml

https://tools.hmcts.net/jira/browse/EM-4224
Resolved local setup issue with addition of AM API
```
[ ] Yes
[X] No
```

Resolved local setup issue with addition of AM API

---

src/main/resources/bundleconfiguration/iac-hearing-bundle-config.yaml

[RIA-4926](https://tools.hmcts.net/jira/browse/RIA-4926)
See Jira
Update to generate hearing bundle template to cater for AIP citizen journey.
```
[ ] Yes
[x] No
```

RIA-4926 updated hearing bundle template

---

build.gradle

https://tools.hmcts.net/jira/browse/EM-4264
Resolve CVE's for EM API's (CVE-2021-42550, CVE-2021-43797, CVE-2022-23181)
```
[ ] Yes
[X] No
```

Resolve CVE's

---

charts/em-ccdorc/Chart.yaml

https://tools.hmcts.net/jira/browse/EM-4268
Update helm chart
```
[ ] Yes
[X] No
```

Update helm chart

---

config/owasp/dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/EM-4275
Removed suppression
```
[ ] Yes
[X] No
```

Removed suppression

---

src/main/resources/bundleconfiguration/sscs-bundle-config.yaml
src/main/resources/bundleconfiguration/sscs-bundle-edited-config.yaml
src/main/resources/bundleconfiguration/sscs-bundle-welsh-config.yaml
src/main/resources/bundleconfiguration/sscs-bundle-welsh-edited-config.yaml

https://tools.hmcts.net/jira/browse/SSCS-10147
Changed folder name
```
[ ] Yes
[x] No
```

SSCS-10147changed folder name

---

database/Dockerfile
docker-compose-dependencies.yml

https://tools.hmcts.net/jira/browse/EM-4290
update postgres version to 11 for local setup
```
[ ] Yes
[X] No
```

update postgres version to 11 for local setup

---

charts/em-ccdorc/Chart.yaml

bump java chart
```
[ ] Yes
[X] No
```

bump java chart

---

build.gradle
config/owasp/dependency-check-suppressions.xml
src/main/java/uk/gov/hmcts/reform/em/orchestrator/Application.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/config/SwaggerConfiguration.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/config/security/SecurityConfiguration.java

https://tools.hmcts.net/jira/browse/EM-4293
Upgraded SpringBoot version to 2.6.4
```
[ ] Yes
[X] No
```

Upgraded SpringBoot version to 2.6.4

---

build.gradle
src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/orchestratorcallbackhandler/CcdCallbackBundleUpdaterTest.java

Changed fasterXmlJackson version from 2.12.5 to 2.13.2

---

src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/orchestratorcallbackhandler/CcdCallbackBundleUpdaterTest.java

Fix the failing test in CcdCallbackBundleUpdaterTest
```
[ ] Yes
[X] No
```

Fix the failing test in CcdCallbackBundleUpdaterTest

---

.github/dependabot.yml

https://tools.hmcts.net/jira/browse/EM-4331
Updated dependabot.yml
```
[ ] Yes
[X] No
```

Updated dependabot.yml

---

src/main/resources/application.yaml

N/A
Removed unused S2S keys - jui_webapp,pui_webapp
```
[ ] Yes
[X] No
```

Removed unused S2S keys - jui_webapp,pui_webapp

---

README.md
src/main/java/uk/gov/hmcts/reform/em/orchestrator/config/SwaggerConfiguration.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/CcdCloneBundleController.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/CcdStitchBundleCallbackController.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/NewBundleController.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/StitchingCompleteCallbackController.java
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/EM-4395
Updated Swagger doc
```
[ ] Yes
[X] No
```

Updated Swagger doc

---

build.gradle

https://tools.hmcts.net/jira/browse/EM-4462
Fix CVE-2022-22978
```
[ ] Yes
[X] No
```

Fix CVE-2022-22978

---

src/main/java/uk/gov/hmcts/reform/em/orchestrator/config/Constants.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/CachedBodyHttpServletRequest.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/CachedBodyServletInputStream.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/ContentCachingFilter.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/ServiceNameAspect.java
src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/CachedBodyHttpServletRequestUnitTest.java
src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/CachedBodyServletInputStreamUnitTest.java
src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/ContentCachingFilterUnitTest.java
src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/ServiceNameAspectTest.java

https://tools.hmcts.net/jira/browse/EM-4476
Updated the logic to log the caseId for each request
```
[ ] Yes
[X] No
```

Updated the logic to log the caseId for each request

---

build.gradle
src/aat/java/uk/gov/hmcts/reform/em/orchestrator/testutil/ExtendedCcdHelper.java
src/aat/java/uk/gov/hmcts/reform/em/orchestrator/testutil/TestUtil.java
src/aat/resources/application.yml
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/EM-4470
Added in changes for CFTLib. Dependencies consumed are run Stitching API.
```
[ ] Yes
[X] No
```

Added in changes for CFTLib

---

build.gradle
src/main/java/uk/gov/hmcts/reform/em/orchestrator/stitching/StitchingService.java

https://tools.hmcts.net/jira/browse/EM-4493
Added in more logs to troubleshoot prod issue for Civil service.
```
[ ] Yes
[X] No
```

Added in more logs to troubleshoot prod issue

---

build.gradle
src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/AutomatedCaseUpdater.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/AutomatedStitchingExecutor.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/AsyncCcdBundleStitchingService.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/CcdBundleStitchingService.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/DefaultUpdateCaller.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/ccdcallbackhandler/CcdCallbackDto.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/stitching/StitchingService.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/stitching/dto/CdamDto.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/stitching/dto/DocumentTaskDTO.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/util/StringUtilities.java
src/test/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/AutomatedStitchingExecutorTest.java
src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/AsyncCcdBundleStitchingServiceTest.java
src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/CcdBundleStitchingServiceTest.java
src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/DefaultUpdateCallerTest.java
src/test/java/uk/gov/hmcts/reform/em/orchestrator/stitching/StitchingServiceTest.java

https://tools.hmcts.net/jira/browse/EM-4493
Updated the logic to populate the cdam details to resolve the issue of http-request/session.
```
[ ] Yes
[X] No
```

Updated the logic to populate the cdam details

---

build.gradle
config/owasp/dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/EM-4515
Updated springboot & dependents lib version.
Removed redundant cve suppression.
```
[ ] Yes
[X] No
```

Updated springboot version & removed redundant cve suppression

---

src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/AutomatedBundlingScenarios.java
src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/CcdStitchScenarios.java
src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/SecureCcdStitchScenarios.java
src/aat/java/uk/gov/hmcts/reform/em/orchestrator/testutil/TestUtil.java
src/aat/resources/application.yml
src/aat/resources/custom-documents-case.json
src/aat/resources/multi-bundle-case.json
src/aat/resources/non-custom-documents-case.json
src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/AutomatedCaseUpdater.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/AutomatedStitchingExecutor.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/AsyncCcdBundleStitchingService.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/DefaultUpdateCaller.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/ccdcallbackhandler/CcdCallbackDto.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/ccdcallbackhandler/CcdCallbackResponseDto.java
src/test/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/AutomatedStitchingExecutorTest.java

https://tools.hmcts.net/jira/browse/EM-4516
Use document task id and polling to test async stitch
```
[ ] Yes
[x] No
```

Use document task id and polling to test async stitch

---

src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/ServiceNameAspect.java

https://tools.hmcts.net/jira/browse/EM-4560
Resolve service exception
```
[ ] Yes
[x] No
```

Resolve service exception

---

.github/renovate.json
src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/AutomatedBundlingWithCallbacks.java
src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/SecureAutomatedBundlingWithCallbacks.java

https://tools.hmcts.net/jira/browse/DTSPO-10093
Updated renovate config
```
[ ] Yes
[X] No
```

Updated renovate config

---

build.gradle

https://tools.hmcts.net/jira/browse/EM-4585
Merged bot prs in to one.
```
[ ] Yes
[X] No
```

Merged bot prs in to one

---

build.gradle

EM-4227 fix pitest

---

build.gradle

- EM-CCD-Orchestrator-CVE-Fix
```
[ ] Yes
[ x] No
```

[EM-4609]-EM-CCD-Orchestrator-CVE-Fix

---

build.gradle
src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/AutomatedBundlingScenarios.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/NewBundleController.java
src/test/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/NewBundleControllerTest.java

https://tools.hmcts.net/jira/browse/EM-3712
Change response code for errored responses to 400
```
[ ] Yes
[x] No
```

Change response status code

---

build.gradle
config/owasp/dependency-check-suppressions.xml
src/main/resources/bundleconfiguration/sample-config.yaml

This is the sample config file to test the bundling feature
FPET-148
```
[ ] Yes
[X ] No
```

prl bundling test yaml config changes

---

src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/EM-4579
Whitelisted prl_cos_api to access non-prod env
```
[ ] Yes
[X] No
```

Whitelisted prl_cos_api to access non-prod env

---

src/main/resources/bundleconfiguration/sample-config.yaml

FPET-148
Fixed the path issue
```
[ ] Yes
[ x] No
```

path corrected for bundling config changes

---

src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/CcdStitchScenarios.java
src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/SecureCcdStitchScenarios.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/CcdCloneBundleController.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/CcdStitchBundleCallbackController.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/NewBundleController.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/DefaultUpdateCaller.java
src/test/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/NewBundleControllerTest.java
src/test/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/DefaultUpdateCallerTest.java

EM-3699 return 400 error for bad requests.

EM-3699 return 400 error for bad requests.

---

src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/ccdapi/CcdDataApiCaseUpdater.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/notification/NotificationService.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/stitching/StitchingService.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/stitching/StitchingServiceException.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/util/HttpOkResponseCloser.java

[EM-4694](https://tools.hmcts.net/jira/browse/EM-4694) close response

EM-4694 close response

---

charts/em-ccdorc/Chart.yaml
charts/em-ccdorc/values.yaml

N/A
Moved S2S list to values.yaml. This will make whitelisting of new services on to Non-Prod & Prod environment more flexible.
```
[ ] Yes
[X] No
```

Moved S2S list to values.yaml

---

charts/em-ccdorc/Chart.yaml
charts/em-ccdorc/values.yaml

https://tools.hmcts.net/jira/browse/EM-4750
Whitelisted sptribs_case_api for non-prod environments
```
[ ] Yes
[X] No
```

Whitelisted sptribs_case_api for non-prod environments

---

src/main/java/uk/gov/hmcts/reform/em/orchestrator/util/HttpOkResponseCloser.java

[EM-479](https://tools.hmcts.net/jira/browse/EM-4790)0 check response before close

EM-4790 check response before close

---

src/main/resources/bundleconfiguration/prl-bundle-config.yaml

https://tools.hmcts.net/jira/browse/FPET-231
PRL bundle configuration
```
[ ] Yes
[ X] No
```

prl bundle config changes(ready for merge)

---

src/main/resources/bundleconfiguration/prl-bundle-config.yaml

https://tools.hmcts.net/jira/browse/FPET-231
```
[ ] Yes
[ X] No
```

Modified prl yaml file as per the new requirements

---

src/main/resources/bundleconfiguration/prl-bundle-config.yaml

https://tools.hmcts.net/jira/browse/FPET-231
```
[ ] Yes
[ X] No
```

Refactoring mappings  as per new suggestions

---

src/main/resources/bundleconfiguration/prl-bundle-config.yaml

Refactoring the PRL Bundling folders 

---

src/main/resources/bundleconfiguration/prl-bundle-config.yaml

Refactoring changes for fixes(READY FOR MERGE)

---

charts/em-ccdorc/Chart.yaml
src/main/resources/bundleconfiguration/prl-bundle-config.yaml

https://tools.hmcts.net/jira/browse/FPET-231
```
[ ] Yes
[ X] No
```

PRLBundle changes(READY FOR MERGE)

---

src/aat/resources/application.yml

https://tools.hmcts.net/jira/browse/EM-4919
Change default url
```
[ ] Yes
[x] No
```

Change default url

---

infrastructure/variables.tf

fix master build

---

src/main/resources/bundleconfiguration/sscs-bundle-config.yaml
src/main/resources/bundleconfiguration/sscs-bundle-edited-config.yaml
src/main/resources/bundleconfiguration/sscs-bundle-welsh-config.yaml
src/main/resources/bundleconfiguration/sscs-bundle-welsh-edited-config.yaml

Updated the SSCS Cover Letter

---

src/main/resources/bundleconfiguration/caseprogression-bundle-config.yaml

https://tools.hmcts.net/jira/browse/CIV-5796
updated filter for SDO and updated coverpage
```
[ ] Yes
[ ] No
```

updated coverpage and sdo filter

---

src/main/resources/bundleconfiguration/caseprogression-bundle-config.yaml

https://tools.hmcts.net/jira/browse/CIV-5796
reverted coverpage template name
```
[ ] Yes
[ ] No
```

updated caseprogression yaml

---

src/main/resources/bundleconfiguration/caseprogression-bundle-config.yaml

https://tools.hmcts.net/jira/browse/CIV-7573
Corrected folder names
```
[ ] Yes
[ ] No
```

CIV-7573 corrected typos

---

Dockerfile
build.gradle

EM-5170-avoid-vulnerability

---

src/main/resources/bundleconfiguration/caseprogression-bundle-config.yaml

Update case progression config for testing
```
[ ] Yes
[ ] No
```

update case progression config

---

audit.json

EM-5186 suppress security vulnerability

EM-5186 suppress security vulnerability

---

src/main/resources/bundleconfiguration/caseprogression-bundle-config.yaml

Removed temporary change done for testing sections and set hasFolderCoversheets to false
```
[ ] Yes
[ ] No
```

CIV-7573 add testing changes

---

src/main/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/NewBundleController.java

N/A
Removed log line.
```
[ ] Yes
[X] No
```

Removed log line

---

src/main/resources/bundleconfiguration/st_cic_bundle_all_case.yaml

https://tools.hmcts.net/jira/browse/ST-1388
ST CIC bundle config file
```
[ ] Yes
[x] No
```

ST-1388 ST CIC bundle config file

---

build.gradle

EM-5117 spring 3 upgrade- remove javax.el

---

src/aat/java/uk/gov/hmcts/reform/em/orchestrator/smoke/SmokeTest.java

EM-5117 spring 3 upgrade- remove spring boot test from smoke test

EM-5117 spring 3 upgrade- remove spring boot test from smoke test

---

build.gradle

EM-5117 spring 3- arrange jackson dependency

EM-5117 spring 3- arrange jackson dependency

---

charts/em-ccdorc/values.preview.template.yaml

EM-5300 override appinsight access

EM-5300 override appinsight access

---

src/aat/java/uk/gov/hmcts/reform/em/orchestrator/testutil/TestUtil.java
src/aat/resources/application.yml
src/main/java/uk/gov/hmcts/reform/em/orchestrator/stitching/StitchingService.java
src/main/resources/application.yaml

Em-5118 remove "/" from URL

---

charts/em-ccdorc/Chart.yaml
charts/em-ccdorc/values.yaml
src/main/resources/application.yaml
src/main/resources/bundleconfiguration/et-dcf-2.yaml
src/main/resources/bundleconfiguration/et-dcf-ordered.yaml

https://tools.hmcts.net/jira/browse/RET-3917
Added 2 ET/ECM bundle configurations plus ET and ECM to whitelists
```
[ ] Yes
[ ] No
```

RET-3917 - Onboard ET and ECM to EM Bundling tools

---

src/main/resources/bundleconfiguration/caseprogression-bundle-config.yaml

Update case progression yaml according to the bundles new structure  CIV-7950
```
[ ] Yes
[ ] No
```

CVI-7950 update case progression yaml

---

src/main/resources/bundleconfiguration/st_cic_bundle_all_case.yaml

https://tools.hmcts.net/jira/browse/ST-1388
```
[ ] Yes
[ ] No
```

ST-1388 documentType to category_id

---

audit.json

https://tools.hmcts.net/jira/browse/EM-5488
added 1 fingerprint to audit.json

em-5488: added 1 fingerprint to audit.json

---

src/main/resources/bundleconfiguration/caseprogression-bundle-config.yaml

Remove filename as we only want filename specified in identifier
resolved CL2 disclosure file name issue
```
[ ] Yes
[ ] No
```

CIV-7950 remove filename and corrected CL2 disclosure file name

---

src/main/resources/bundleconfiguration/caseprogression-bundle-config.yaml

Added filename again since without that stitched.pdf is getting appended after filenameIdentifier
```
[ ] Yes
[ ] No
```

CIV-7950 update file name

---

src/main/resources/bundleconfiguration/caseprogression-bundle-config.yaml

Fix stitched pdf file name
```
[ ] Yes
[ ] No
```

CIV-7950 fix file name

---

src/main/java/uk/gov/hmcts/reform/em/orchestrator/stitching/StitchingService.java

https://tools.hmcts.net/jira/browse/EM-5540
Updated log level.
```
[ ] Yes
[X] No
```

Updated log level

---

src/aat/java/uk/gov/hmcts/reform/em/orchestrator/testutil/TestUtil.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/stitching/StitchingService.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/stitching/StitchingTaskMaxRetryException.java

Add custom exception,
IOException is misleading.

Add exception type

---

src/main/resources/bundleconfiguration/st_cic_bundle_all_case.yaml

ST-1388
category_id changed to categoryId
```
[ ] Yes
[x ] No
```

ST-1388 Refactoring category_id to categoryId

---

src/main/resources/bundleconfiguration/st_cic_bundle_all_case.yaml

ST-1388
REfctoring ST CIC Bundle yaml config
```
[ ] Yes
[x ] No
```

ST-1388 Refactoring st_cic Bundle yaml config

---

src/main/resources/bundleconfiguration/st_cic_bundle_all_case.yaml

ST-1388
Fixing typo
```
[ ] Yes
[ x] No
```

ST-1388 Fixing typo

---

.github/renovate.json
config/owasp/dependency-check-suppressions.xml

fix renovate EM-5551

---

lib/applicationinsights.json

EM-5505 reduce logs

---

lib/applicationinsights.json
src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/AutomatedStitchingExecutor.java

EM-5505 reduce welcome logs

---

charts/em-ccdorc/Chart.yaml
charts/em-ccdorc/values.yaml
src/main/resources/application.yaml

Changed service name to test on demo, perf etc before a potential go live

ECM - Changed service name

---

src/main/resources/bundleconfiguration/caseprogression-bundle-config.yaml

https://tools.hmcts.net/jira/browse/CIV-11132
change section of Particulars of Claim

CIV-11132 change section of Particulars of Claim

---

Dockerfile

EM-5649 fix app insight logging

EM-5649 fix app insight logging

---

src/main/resources/bundleconfiguration/et-dcf-2.yaml

https://tools.hmcts.net/jira/browse/RET-3917
Added a custom coversheet for ET/ECM bundles

RET-3917 Update et-dcf-2.yaml

---

src/main/java/uk/gov/hmcts/reform/em/orchestrator/config/security/SecurityConfiguration.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/errors/ExceptionTranslator.java
src/test/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/errors/ExceptionTranslatorIntTest.java
src/test/java/uk/gov/hmcts/reform/em/orchestrator/endpoint/errors/ExceptionTranslatorTestController.java

https://tools.hmcts.net/jira/browse/EM-5406
Stop 403 showing for other error codes

Stop 403 showing for other error codes

---

src/main/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/BundleFactory.java
src/test/java/uk/gov/hmcts/reform/em/orchestrator/automatedbundling/BundleFactoryTest.java
src/test/resources/case-data7.json

EM-5691 add error log

---

src/main/resources/bundleconfiguration/st_cic_bundle_all_case.yaml

testing removal of filter
testing removal of filter

remove filter to test getting it working

---

build.gradle

EM-5715 fix pact test error

---

build.gradle

Em-5715 fix pact test errors

---

build.gradle

bump junit jupiter version

---

build.gradle

Em 5715 fix pact test errors

---

build.gradle

EM-5717 arrange dependency management 

---

charts/em-ccdorc/Chart.yaml
charts/em-ccdorc/values.yaml
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/EM-5724
Removed redundant s2s keys from whitelist.

Removed redundant s2s keys

---

src/main/resources/bundleconfiguration/st_cic_bundle_all_case.yaml

filter -SPtribunals - Ben Guy

---

src/main/resources/bundleconfiguration/st_cic_bundle_all_case.yaml

ST-1711 Changing underscore to hyphen

---

build.gradle
config/owasp/dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/EM-5744
resolve CVE

Em 5744 resolve CVE

---

src/main/resources/bundleconfiguration/prl-bundle-config.yaml

Changing the fileNameIdentifier for Private-law

---

charts/em-ccdorc/Chart.yaml

https://tools.hmcts.net/jira/browse/EM-5950
Updated Java chart to enable HPA config.

Updated Java chart to enable HPA config

---

charts/em-ccdorc/Chart.yaml
charts/em-ccdorc/values.yaml

https://tools.hmcts.net/jira/browse/EM-5989
Disabled Spot instances.

Disabled Spot instances.

---

build.gradle
infrastructure/aat.tfvars
infrastructure/demo.tfvars
infrastructure/ithc.tfvars
infrastructure/main.tf
infrastructure/perftest.tfvars
infrastructure/preview.tfvars
infrastructure/prod.tfvars
infrastructure/sprod.tfvars
infrastructure/variables.tf

https://tools.hmcts.net/jira/browse/DTSPO-17786
- add ia-aat-mi to access policy for aat keyvault

add ia-aat-mi to access policy for aat keyvault

---

infrastructure/aat.tfvars

- add sptribs MI access to aat kv

add sptribs mi access to aat

---

src/aat/resources/application.yml
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/EM-6121
use dummy default key

use dummy default key

---

src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/AsyncCcdBundleStitchingService.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/CcdBundleStitchingService.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/UpdateCase.java

https://tools.hmcts.net/jira/browse/EM-5923
-Added UpdateCase to be used by both AsyncCcdBundleStitchingService and CcdBundleStitchingService to remove duplicate code chunk in both.

Fix code smell by removing duplicate code chunk

---

src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/UpdateCase.java

https://tools.hmcts.net/jira/browse/EM-5923
Updated UpdateCase constructor to be protected

EM-5923 Code smells: protected constructor

---

infrastructure/aat.tfvars

Access for sscs to keyvault in aat

---

build.gradle

Reverts hmcts/em-ccd-orchestrator#1688

Revert "Update dependency au.com.dius.pact.consumer:junit5 to v4.6.14"

---

src/main/resources/bundleconfiguration/iac-updated-hearing-bundle-config.yaml
src/main/resources/bundleconfiguration/iac-updated-hearing-bundle-inc-tribunal-config.yaml

https://tools.hmcts.net/jira/browse/EM-6207
Added in new Bundle config files for IAC.
N/A

Add IAC Bundle config files

---

src/main/resources/bundleconfiguration/sample-config.yaml

https://tools.hmcts.net/jira/browse/FPET-1118
Update sample-config.yaml to use for POC to remove subfolders from PRL bundle

FPET-1118: POC to remove subfolders

---

src/main/resources/bundleconfiguration/sample-config.yaml

https://tools.hmcts.net/jira/browse/FPET-995
Updates sample-config.yaml with new bundle structure for all documents

FPET-995: Update sample-config.yaml to include all documents for bundle

---

src/main/resources/bundleconfiguration/prl-bundle-config.yaml

https://tools.hmcts.net/jira/browse/FPET-995
Copy bundle config from sample-config to prl-bundle-config

FPET-995: Copy bundle config from sample-config to prl-bundle-config

---

src/aat/java/uk/gov/hmcts/reform/em/orchestrator/testutil/TestUtil.java
src/main/java/uk/gov/hmcts/reform/em/orchestrator/stitching/StitchingService.java

https://tools.hmcts.net/jira/browse/EM-6295
check for in progress status for the sync bundling call -/stitch-ccd-bundles

check for in progress

---

src/main/java/uk/gov/hmcts/reform/em/orchestrator/service/caseupdater/InputValidationException.java

[EM-6301](https://tools.hmcts.net/jira/browse/EM-6301) add violations to exception message

EM-6301 add violations to exception message

---

src/main/resources/bundleconfiguration/sample-config.yaml

https://tools.hmcts.net/jira/browse/FPET-1174
Adds FM5 statements to the sample-config bundle configuration.

FPET-1174: Add FM5 statements to sample-config.yaml

---

src/main/resources/bundleconfiguration/prl-bundle-config.yaml

https://tools.hmcts.net/jira/browse/FPET-1174
Adds FM5 statements to prl-bundle-config

FPET-1174: Add FM5 statements to prl-bundle-config.yaml

---

charts/em-ccdorc/Chart.yaml
charts/em-ccdorc/values.yaml

https://tools.hmcts.net/jira/browse/EM-6310
whitelisted civil_general_applications for all non-prod environments.
N/A

whitelisted civil_general_applications

---

gradle/wrapper/gradle-wrapper.properties
src/main/resources/bundleconfiguration/sscs-ib-bundle-config.yaml
src/main/resources/bundleconfiguration/sscs-ib-bundle-edited-config.yaml

See [SSCSCI-1381 ](https://tools.hmcts.net/jira/browse/SSCSCI-1381 )
Adding new bundle config to use new cover letter template for bundles without affecting existing one yet.

SSCSCI-1381

---

src/main/resources/bundleconfiguration/civil-forms-bundle-config.yaml

DTSCCI-1155
Adding civil form config to use async stitch call
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)

DTSCCI-1155: adding civil form config to use async stitch call

---

infrastructure/aat.tfvars

DTSCCI-1155
Access for civil to keyvault in aat
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)

DTSCCI-1155: Access for civil to keyvault in aat

---

build.gradle
src/aat/java/uk/gov/hmcts/reform/em/orchestrator/functional/BaseTest.java
src/aat/java/uk/gov/hmcts/reform/em/orchestrator/smoke/SmokeTest.java

https://tools.hmcts.net/jira/browse/EM-6328
Upgrading serenity to 4.2.9 and updated imports

Upgrade Serenity to 4.2.9

---

build.gradle

https://tools.hmcts.net/jira/browse/EM-6328
Upgraded POI to 5.2.5

Upgrade POI to 5.2.5

---

src/contractTest/java/uk/gov/hmcts/reform/em/orchestrator/IdamConsumerTest.java

https://tools.hmcts.net/jira/browse/EM-6328
Moving pact test spec to V3 to be inline with the idam test provider

IdamConsumerTest moved back to V3 pact spec

---

charts/em-ccdorc/Chart.yaml
charts/em-ccdorc/values.yaml
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/EM-6344
reinstate whitelist for xui_webapp in lower envs as it is needed to run our functional tests with cdam enabled

reinstate whitelist for xui webapp

---

build.gradle

https://tools.hmcts.net/jira/browse/EM-6344
remove junit vintage engine

remove junit vintage engine

---

infrastructure/aat.tfvars

See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
Add ET to managed identity to use EM in preview

Add ET to MI to use in preview

---

src/main/resources/bundleconfiguration/sscs-bundle-config.yaml
src/main/resources/bundleconfiguration/sscs-bundle-edited-config.yaml
src/main/resources/bundleconfiguration/sscs-bundle-welsh-config.yaml
src/main/resources/bundleconfiguration/sscs-bundle-welsh-edited-config.yaml

See [SSCSCI-1548](https://tools.hmcts.net/jira/browse/SSCSCI-1548)

SSCSCI-1548 updating bundle config post-release

---

charts/em-ccdorc/Chart.yaml

https://tools.hmcts.net/jira/browse/EM-6542
Upgrading to oci charts, bumping minor version of chart

EM-6542 Upgrading to oci charts

---

src/main/resources/bundleconfiguration/prl-bundle-config.yaml
src/main/resources/bundleconfiguration/sample-config.yaml

FPVTL-68 Add ChildImpactReport1 and 2
